Table Producto {
    id serial [pk, increment]
    nombre_producto varchar(100) [not null]
    categoria varchar(50) [not null]
    talla varchar(50) [not null]
    color varchar(50) [not null]
    precio_product decimal
    marca varchar(100)

}
Table Tienda {
    id serial [pk, increment]
    nombre_tienda varchar(100) [not null, unique]
    tipo_tienda varchar(50)
    ubicacion varchar(200)
}

Table Cliente {
    id serial [pk, increment]
    nombre_cliente varchar(200) [not null]
    documento integer [not null, unique]
    email varchar(200) [not null, unique]
    telefono varchar(200) [not null]
    pais varchar(100) [not null]
    ciudad varchar(100) [not null]
}

Table Proveedor{
    id serial [pk, increment]
    nombre_proveedor varchar(200) [not null, unique]
    documento integer [not null, unique]
    email varchar(200) [not null, unique]
    telefono varchar(200) [not null]
    pais varchar(100) [not null]
    ciudad varchar(100) [not null]
    tipo_material varchar(200) [not null]
}

Table OrdenDeCompra{
id serial [pk, increment]
id_proveedor integer [not null]
fecha timestamp
estado varchar(50) [not null]
id_producto integer [not null]
nombre_producto varchar(100) [not null]
cantidad integer [not null]
}
Ref: Proveedor.id > OrdenDeCompra.id_proveedor //UN PROVEEDOR TIENE MUCHAS ORDENES DE COMPRA

Table Inventario {
    id serial [pk, increment]
    id_producto integer
    id_tienda integer
    cantidad integer [not null]
    fecha_entrada timestamp
}
Ref: Producto.id-Inventario.id_producto //UN PRODUCTO TIENE UN INVENTARIO
Ref: Tienda.id<Inventario.id_producto// MUCHAS TIENDAS TIENEN UN INVENTARIO
Ref: Producto.id>OrdenDeCompra.id_producto//UN PRODUCTO TIENE MUCHAS ORDENES DE COMPRA

Table Venta {
    id serial [pk, increment]
    id_cliente integer
    id_tienda integer
    fecha_venta timestamp
    metodo_pago varchar(30) [not, null]
    valor_total decimal
}
Ref: Venta.id_cliente-Cliente.id //UNA VENTA TIENE UN CLIENTE
Ref: Venta.id_tienda-Tienda.id //UNA VENTA TIENE UNA TIENDA

Table DetalleVenta {
    id serial [pk, increment]
    id_venta integer
    id_producto integer
    cantidad integer
    precio_unitario decimal
}
Ref: DetalleVenta.id_venta-Venta.id //DETALLE VENTA PERTENECE A UNA VENTA
Ref: Producto.id<DetalleVenta.id_producto//UN PRODUCTO TIENE MUCHOS DETALLES DE VENTA

Table Envio {
    id serial [pk, increment]
    id_venta integer
    transportadora varchar(200) [not null]
    numero_guia varchar(50) [not null, unique]
    fecha_envio timestamp [not null] 
}
Ref: Envio.id_venta-Venta.id //Un Envio Tiene Una venta

Table Factura {
    id serial [pk, increment]
    id_venta integer
    valor_total decimal
    moneda varchar(50) [not null]
    impuestos decimal
    descuentos decimal
    fecha_emision timestamp
}
Ref: Factura.id_venta-Venta.id //Una Factura Pertenece a Una venta

Table Pagos {
    id serial [pk, increment]
    id_factura integer
    id_venta integer
    metodo_pago varchar(50) [not null]
    estado varchar(50) [not null]
}
Ref: Pagos.id_factura-Factura.id //UN PAGO PERTENECE A UNA FACTURA
Ref: Pagos.id_venta-Venta.id //UN PAGO PERTENECE A UNA VENTA
