Enum user_role{
    admin
    customer
    guest
}


Table users {
id serial [pk, increment]
username varchar(50) [not null, unique]
password varchar(255) [not null]
email varchar [unique, not null]
role user_role [not null] // "admin, customer"
is_active boolean [not null, default: true] //USUARIO ACTIVO
name_job varchar(100) [default: 'UNICUCES']//TEXTO POR DEFECTO
created_at timestamp [default: 'now()', not null] //fecha de registro
update_at timestamp //fecha de actualizacion de campos
balance decimal(10,2) [default: 0.00] //maximo de numeros y maximo de decimales
serial_number integer
}
